[package]
name = "cargo-jk"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
windows = { version = "0.61.3", features = [
    "Win32_Foundation",
    "Win32_UI_Shell"
] }